### ISSUE TITLE
commit시 설명란에 #번호 

### ISSUE THREAD

**Issue by wlwhsxz** [jhparkland/Age_Friendly_City#176]
**Description**
```
만약 Issues에 언급된 내용을 수정하고 이를 commit시,
첨부 사진처럼 설명란에 #번호를 적어주시면 변경사항 참고에 용이할 듯 합니다 ^^
```
![image](https://user-images.githubusercontent.com/49461207/163557693-9a6974b5-082b-4943-ab42-b392a4445d59.png)

**Comment by klavna** [comment]
참고하겠습니다.

**Comment by wlwhsxz** [comment]
다른 기여자들이 참고할 수 있도록 당분간 open issue로 남겨두도록 하겠습니다.
