### ISSUE TITLE
국가별 65세 이상 인구비율 도달년도

### ISSUE THREAD

**Issue by sj2305** [jhparkland/Age_Friendly_City#243]
<html>
<body>

<table class="">
   <tr>
   <th class="" rowspan="2">&nbsp;&nbsp;국가</th>
   <th class="" colspan="8">65세 이상 인구 비율（도달년도)</th>
   <th class="" colspan="2">소요년수</th>
   </tr>
   <tr>
   <td class="tg-0lax">7%</td>
   <td class="tg-0lax">10%</td>
   <td class="tg-0lax">14%</td>
   <td class="tg-0lax">15%</td>
   <td class="tg-0lax">20%</td>
   <td class="tg-0lax">21%</td>
   <td class="tg-0lax">25%</td>
   <td class="tg-0lax">30%</td>
   <td class="tg-0lax">7%→14%</td>
   <td class="tg-0lax">10%→20%</td>
   </tr>
   <tr>
   <td class="tg-0lax">한국</td>
   <td class="tg-0lax">2000</td>
   <td class="tg-0lax">2009</td>
   <td class="tg-0lax">2018</td>
   <td class="tg-0lax">2019</td>
   <td class="tg-0lax">2026</td>
   <td class="tg-0lax">2027</td>
   <td class="tg-0lax">2032</td>
   <td class="tg-0lax">2039</td>
   <td class="tg-0lax">18</td>
   <td class="tg-0lax">17</td>
   </tr>
   <tr>
   <td class="tg-0lax">일본</td>
   <td class="tg-0lax">1970</td>
   <td class="tg-0lax">1985</td>
   <td class="tg-0lax">1994</td>
   <td class="tg-0lax">1996</td>
   <td class="tg-0lax">2005</td>
   <td class="tg-0lax">2007</td>
   <td class="tg-0lax">2013</td>
   <td class="tg-0lax">2025</td>
   <td class="tg-0lax">24</td>
   <td class="tg-0lax">20</td>
   </tr>
   <tr>
   <td class="tg-0lax">중국</td>
   <td class="tg-0lax">2001</td>
   <td class="tg-0lax">2016</td>
   <td class="tg-0lax">2025</td>
   <td class="tg-0lax">2027</td>
   <td class="tg-0lax">2034</td>
   <td class="tg-0lax">2036</td>
   <td class="tg-0lax">2046</td>
   <td class="tg-0lax">2057</td>
   <td class="tg-0lax">24</td>
   <td class="tg-0lax">18</td>
   </tr>
   <tr>
   <td class="tg-0lax">독일</td>
   <td class="tg-0lax">1932</td>
   <td class="tg-0lax">1952</td>
   <td class="tg-0lax">1972</td>
   <td class="tg-0lax">1976</td>
   <td class="tg-0lax">2008</td>
   <td class="tg-0lax">2015</td>
   <td class="tg-0lax">2027</td>
   <td class="tg-0lax">2040</td>
   <td class="tg-0lax">40</td>
   <td class="tg-0lax">56</td>
   </tr>
   <tr>
   <td class="tg-0lax">영국</td>
   <td class="tg-0lax">1929</td>
   <td class="tg-0lax">1946</td>
   <td class="tg-0lax">1975</td>
   <td class="tg-0lax">1981</td>
   <td class="tg-0lax">2025</td>
   <td class="tg-0lax">2028</td>
   <td class="tg-0lax">2048</td>
   <td class="tg-0lax">2097</td>
   <td class="tg-0lax">46</td>
   <td class="tg-0lax">79</td>
   </tr>
   <tr>
   <td class="tg-0lax">이탈리아</td>
   <td class="tg-0lax">1927</td>
   <td class="tg-0lax">1964</td>
   <td class="tg-0lax">1988</td>
   <td class="tg-0lax">1991</td>
   <td class="tg-0lax">2008</td>
   <td class="tg-0lax">2012</td>
   <td class="tg-0lax">2024</td>
   <td class="tg-0lax">2033</td>
   <td class="tg-0lax">61</td>
   <td class="tg-0lax">44</td>
   </tr>
   <tr>
   <td class="tg-0lax">미국</td>
   <td class="tg-0lax">1942</td>
   <td class="tg-0lax">1970</td>
   <td class="tg-0lax">2014</td>
   <td class="tg-0lax">2016</td>
   <td class="tg-0lax">2029</td>
   <td class="tg-0lax">2034</td>
   <td class="tg-0lax">2070</td>
   <td class="tg-0lax">-</td>
   <td class="tg-0lax">72</td>
   <td class="tg-0lax">59</td>
   </tr>
   <tr>
   <td class="tg-0lax">스웨덴</td>
   <td class="tg-0lax">1887</td>
   <td class="tg-0lax">1948</td>
   <td class="tg-0lax">1972</td>
   <td class="tg-0lax">1975</td>
   <td class="tg-0lax">2018</td>
   <td class="tg-0lax">2025</td>
   <td class="tg-0lax">2055</td>
   <td class="tg-0lax">-</td>
   <td class="tg-0lax">85</td>
   <td class="tg-0lax">70</td>
   </tr>
   <tr>
   <td class="tg-0lax">프랑스</td>
   <td class="tg-0lax">1864</td>
   <td class="tg-0lax">1943</td>
   <td class="tg-0lax">1979</td>
   <td class="tg-0lax">1995</td>
   <td class="tg-0lax">2018</td>
   <td class="tg-0lax">2021</td>
   <td class="tg-0lax">2035</td>
   <td class="tg-0lax">2095</td>
   <td class="tg-0lax">115</td>
   <td class="tg-0lax">75</td>
   </tr>
   </table>

</body>
</html>

**Comment by sj2305** [comment]
출처 : https://www.kfpa.or.kr/webzine/202003/sub/disasters1.html

**Comment by sj2305** [comment]
한국이 고령화 속도가 제일 빠르며 앞으로도 계속 빨라질 것이라는 것을 알 수 있습니다.
출처 : https://www.kfpa.or.kr/webzine/202003/sub/disasters1.html

**Comment by wlwhsxz** [comment]
@sj2305 해당 내용 pull req - merge 진행 되었나요 =]?

**Comment by sj2305** [comment]
> @sj2305 해당 내용 pull req - merge 진행 되었나요 =]?

위 내용을 '수집자료 / 데이터셋/' 경로에 md 파일로 추가하였습니다.
