### ISSUE TITLE
issues 정리

### ISSUE THREAD

**Issue by rolling1231** [jhparkland/Age_Friendly_City#244]
오래된 issue임에도 closed 되지 않은게 많은 것 같습니다.
일주일간 변화나 개선이 없는 issue의 경우에 다른 사람이 closed해도 될까요?

**Comment by Telettubi** [comment]
이미 몇개정도 변화가 없거나 끝난거같은 issue의 경우 제가 몇개 close를 하긴했는데 
해도 괜찮을 것 같습니다.

**Comment by sj2305** [comment]
다른 저장소에서도 나왔던 의견인데 너무 많은 이슈 내용이 올라오게되면
정작 중요한 내용들을 찾기가 힘들 것으로 예상됩니다. 
이슈가 해결되었거나 도무지 해결하기 힘든 이슈들은 최대한 빨리 닫는것이 좋아보입니다.

**Comment by wlwhsxz** [comment]
그럼 우선, '~하면 좋겠다.' 라는 이슈 중 다른 코멘트 없이 일주일 이상 지난 항목들은 임의로 close 하여 정리하도록 하겠습니다 !

**Comment by wlwhsxz** [comment]
@rolling1231 우선순위가 낮다고 생각되는 7일 이상 지난 + 단순 아이디어 제시 Issues들은 close 진행했습니다.
확인 후 피드백 감사하겠습니다 =]

**Comment by rolling1231** [comment]
확인했습니다.
추가적으로 답장이 없는 이슈는 closed해도 될 것 같으며, 남겨야 하는 내용들은 coc로 옮기면 될 것 같습니다.
