### ISSUE TITLE
고령화의 요인을 알아보았습니다.

### ISSUE THREAD

**Issue by Donghan1** [jhparkland/Age_Friendly_City#248]
## 고령화의 요인
- 고령화의 요인은 저 출산으로 인한 구조적 변화와 평균 수명의 연장을 들 수 있습니다.
- 또한 출생률을 감소하지만 의료기술이 크게 발전함에 따라 고령자의 인구가 폭증함으로 인해 고령화가 발생한다 볼 수 있습니다.

**Comment by wlwhsxz** [comment]
@Donghan1 해당 내용에 대한 출처가 있어야 될 듯 합니다.
