### ISSUE TITLE
고령화와 관련해서 참고 사이트 및 논문을 조사 해보았습니다.

### ISSUE THREAD

**Issue by Donghan1** [jhparkland/Age_Friendly_City#250]
## 정책 프레임워크
WHO Age-friendly Cities Framework:(https://extranet.who.int/agefriendlyworld/): WHO 고령친화 세계에 대한 도시정책 프레임워크

## 데이터 저장소
부산시 어르신 맞춤형데이터 저장소:(https://data.busan.go.kr/customData/list.nm?apitype=130)

## 데이터셋
전국건강증진센터표준데이터:(https://data.busan.go.kr/dataSet/detail.nm?contentId=10&publicdatapk=OA_SS00034)

## 참고사이트
자연어처리:(https://insikk.github.io/awesome-korean-nlp/)

## 관련논문
[고령친화형 도시개발정책에 관한 연구 : 도시재생정책을 중심으로 = (A)study on senior-friendly urban development policy]
(https://m.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&control_no=223805fec55c6e1fffe0bdc3ef48d419&keyword=%EA%B3%A0%EB%A0%B9%EC%B9%9C%ED%99%94%EB%8F%84%EC%8B%9C#redirect)

**Comment by merjunemong** [comment]
관련논문은 예외지만 정책 프레임워크~참고사이트는 README.md #1 버전과 내용이 일치한 거 같습니다.

**Comment by wlwhsxz** [comment]
> 관련논문은 예외지만 정책 프레임워크~참고사이트는 README.md #1 버전과 내용이 일치한 거 같습니다.

동의합니다.

**Comment by wlwhsxz** [comment]
@Donghan1  해당 issue 또한 개인 branch로 파일 옮긴 뒤, close 해주시면 감사하겠습니다 =]
