### ISSUE TITLE
고령친화도시 부산, 참고자료

### ISSUE THREAD

**Issue by qpwery** [jhparkland/Age_Friendly_City#254]
부산의 강점을 이용해 고령친화도시를 발전해 나갈 수 있다고 생각합니다. 
이에 도움 되는 참고자료를 찾았습니다.

[부산, 국내도시 4번째 WHO 고령친화도시 네트워크 가입 부산과 지구촌 고령·도시화 문제 … 국제사회 공동대응](https://www.busan.go.kr/news/snsbusan01/view?dataNo=56969)

**Comment by wlwhsxz** [comment]
해당 자료들은 Issues 에 등록되기 보다
개인 branch 에 자료를 모아 정리한 뒤,
어떤 방향으로 사용 될지 제시하며 파일으로 pull request를 하는 것이 더 바람직해 보입니다.
