### ISSUE TITLE
contribution guideline내용 추가

### ISSUE THREAD

**Issue by Roniebin** [jhparkland/Age_Friendly_City#258]
지금까지 나온 내용들 종합하여 내용 생성 및 추가하였습니다. 혹시 피드백이나 추가할 내용있으면 수정 부탁드립니다.

#229 @wlwhsxz

**Comment by wlwhsxz** [comment]
@Roniebin 감사합니다 =]
내용 확인 후 간단한 수정하였습니다.
수정 사항 확인 후, 의견 부탁 드리겠습니다 =]

**Comment by wlwhsxz** [comment]
@Roniebin 추가 피드백 혹은 수정 사항 없으시면 close 해주셔도 될 듯 합니다 =]
