### ISSUE TITLE
규칙 제안: issue 제목 규칙화 제안

### ISSUE THREAD

**Issue by qpwery** [jhparkland/Age_Friendly_City#259]
여러 내용의 issue를 매번 다 확인하기는 힘들 것입니다.
이에, issue의 제목만 보고 내용 유추가 가능하도록 issue의 제목 앞 부분을 통일하는 것을 제안합니다.
제목을 규칙화한다면, 한눈에 파악하기 쉬울 뿐만 아니라 중복되는 내용이 올라오지 않을 것입니다.

예시)
자료 추가와 관련된 내용의 issue라면, issue의 제목은 "**자료 추가: (세부내용)**"으로 통일.

**Comment by wlwhsxz** [comment]
찬성합니다, 좋은 방안인 듯 합니다 =]
+ **Labels**를 설정하여 도움을 요청하는 이슈인지, 의견을 제시하는 이슈인지 등등 구분

**Comment by wlwhsxz** [comment]
해당 내용 wiki 페이지에 추가하였습니다.
내용 확인 후 수정 할 사항 있으면 수정 후 코멘트 남겨주시면 감사하겠습니다 =]
[wiki링크](https://github.com/pwjdgus/Age_Friendly_City/wiki/Contribution-guideline)

**Comment by wlwhsxz** [comment]
#229

**Comment by Castlemincode** [comment]
저 또한 그 의견에 찬성하는 바이므로 issue할 때 제목에 중시하도록 하겠습니다.
