### ISSUE TITLE
대한민국 노인가구의 현황

### ISSUE THREAD

**Issue by Donghan1** [jhparkland/Age_Friendly_City#265]
- 노인가구의 35.1% 가 1인가구 라고 합니다.
- 지난해 독거노인은 166만1000가구로 전체고령자 가구의 35.1%가 차지하였으며 혼자 사는 노인가구는 70대의 비중이44.1%로 가장 높고 그중 여성분이 71.9%를 차지한다고 합니다. 
-이렇게 혼자사는 노인의 17.1%가 건강상태가 좋다고 알려졌습니다.
-이렇게 혼자 사시는 노인의 인구가 증가할 수록 위험한 상황들이 많이 일어날 것이라고 생각합니다.

**Comment by Donghan1** [comment]
출처 : https://www.100ssd.co.kr/news/articleView.html?idxno=81109

**Comment by wlwhsxz** [comment]
해당 자료들은 Issues 에 등록되기 보다
개인 branch 에 자료를 모아 정리한 뒤, 
어떤 방향으로 사용 될지 제시하며 파일으로써 pull request를 하는 것이 더 바람직해 보입니다.
