### ISSUE TITLE
대한민국 고령화 심각성

### ISSUE THREAD

**Issue by Donghan1** [jhparkland/Age_Friendly_City#266]
-대한민국은 2045년이 되면 세계에서 65세 이상 고령인구 비중이 가장 높은 국가가 됩니다.
-한국의 고령인구 비중은 2019년에 14.9%에서 2067년 46.5%까지 전 세계에서 가장 빠른 속도로 커질 예정 입니다.
- 생산연령인구 100명당 부양할 65세 이상 고령인구는 2019년에 20.4명에서 2067년 102.4명으로 5배 급증할 것입니다. 
- 이처럼 대한민국은 앞으로 시간이 지날 수록 더욱 심각한 고령화 문제를 겪을 것 입니다. 따라서 고령화를 완화 할 수 있는 방안을 하루빨리 찾아야합니다.

**Comment by Donghan1** [comment]
출처 : https://www.yna.co.kr/view/AKR20190902080800002

**Comment by wlwhsxz** [comment]
해당 자료들은 Issues 에 등록되기 보다
개인 branch 에 자료를 모아 정리한 뒤, 
어떤 방향으로 사용 될지 제시하며 파일으로써 pull request를 하는 것이 더 바람직해 보입니다.
