### ISSUE TITLE
고령화의 해결방안을 제시하는것이 필요하다 생각합니다.

### ISSUE THREAD

**Issue by Donghan1** [jhparkland/Age_Friendly_City#270]
고령화 문제가 심각한 만큼 고령화를 해결하기 위한 자세 및 노력을 조사 할 수 있는 issue가 있으면 좋겠습니다.

**Comment by wlwhsxz** [comment]
이슈 작성에 관한
[기여 가이드라인](https://github.com/pwjdgus/Age_Friendly_City/wiki/Contribution-Guidelines) 참고 바랍니다.
