### ISSUE TITLE
git clone 시 문제 발생 : main branch 직접 변경 동의 요청

### ISSUE THREAD

**Issue by wlwhsxz** [jhparkland/Age_Friendly_City#282]
**Description**  
-  폴더명을 일괄적으로 바꾸기 위하여 local 환경에서 git 으로 작업을 진행하려고 합니다.
허나, clone 과정에서 계속하여 아래와 같은 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/49461207/171002349-1a2c2ea0-de8b-4a13-b739-93209be9bab7.png)
***
- [`참고 블로그`](https://velog.io/@ss-won/bugs-Git-%ED%8C%8C%EC%9D%BC%EB%AA%85%EC%97%90-%EC%9D%98%ED%95%9C-pullcheckout-%EC%98%A4%EB%A5%98error-invalid-path-file-path)를 통하여 파일 명에 특수문자가 들어가면 운영체제의 보호 시스템 정책으로 인하여 해당 문제가 발생한다는 것을 알게 되었습니다.  
  
![image](https://user-images.githubusercontent.com/49461207/171003551-c806a6df-e98a-469e-975a-31258896ec85.png)
***
그리하여, 해당 문제를 수월하게 해결하기 위하여 문제로 예상되는 폴더/파일명들을
### main branch에서 직접 변경함에 있어 여러분들의 동의를 구하고자 합니다.

**Comment by wlwhsxz** [comment]
[참고 블로그 주소](https://velog.io/@ss-won/bugs-Git-%ED%8C%8C%EC%9D%BC%EB%AA%85%EC%97%90-%EC%9D%98%ED%95%9C-pullcheckout-%EC%98%A4%EB%A5%98error-invalid-path-file-path)

**Comment by merjunemong** [comment]
원활한 clone과정을 위해 main branch를 직접 변경하는것에 동의합니다

**Comment by wlwhsxz** [comment]
> 원활한 clone과정을 위해 main branch를 직접 변경하는것에 동의합니다

해당 폴더/파일이 포함된 PR건이 있어 이 부분 완료되면 수정할 수 있도록 하겠습니다.
감사합니다 ^^
