### ISSUE TITLE
질문 : 수집자료내의 폴더명 교체

### ISSUE THREAD

**Issue by Roniebin** [jhparkland/Age_Friendly_City#292]
수집자료내의 폴더명중 '노인정보'라는 폴더명이 파일의 분류기준을 모호하게 만드는것같습니다. 혹시 새로운 폴더명이나 분류기준이 있다면 의견 내주시면 감사하겠습니다.

**Comment by wlwhsxz** [comment]
해당 폴더명이 모호한 이유는 해당 폴더 내 파일들을 억지로 한 범주 내로 묶으려는 시도였기 때문인 듯 합니다.
다른 자료 파일들이 더 필요하지는 않을지, 혹은 다른 폴더로 분류 할 순 없을지도 고민해볼 수 있을 듯 합니다.
